### ISSUE TITLE
!?

### ISSUE THREAD

**Issue by tba-adnan** [maskoul-mohamed/learn-java#1]
Virgin jAvA student (you) vs. Chad Assembly conoisseur (me)

![average-chad](https://user-images.githubusercontent.com/92032353/192990632-85d6ab50-c0aa-40de-a502-535fa683bdab.gif)

**Comment by maskoul-mohamed** [comment]
Calm down PhP slave

**Comment by maskoul-mohamed** [comment]
do you mean php doing that with python?

**Comment by maskoul-mohamed** [comment]
not jave :) Kotlin does

**Comment by maskoul-mohamed** [comment]
hachathin solicode again?

**Comment by maskoul-mohamed** [comment]
Ok good luck don't lose this time 😈
